apiVersion: v1
kind: Service
metadata:
  name: {{ include "contoso-air.fullname" . }}
  labels:
    {{- include "contoso-air.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "contoso-air.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
